const devs = [
  {
    id: 1,
    name: "Raj",
    age: 20,
    skill: "Mearn devs",
    location: "Barishal",
    income: 10000,
  },
  {
    id: 2,
    name: "Rabbi",
    age: 18,
    skill: "IOS devs",
    location: "dhaka",
    income: 40000,
  },
  {
    id: 3,
    name: "Rakib",
    age: 60,
    skill: "PHP devs",
    location: "mirpur",
    income: 60000,
  },
  {
    id: 4,
    name: "Shakil",
    age: 55,
    skill: "React devs",
    location: "Barishal",
    income: 70000,
  },
  {
    id: 5,
    name: "Tamim",
    age: 40,
    skill: "BlockChain devs",
    location: "Mirpur",
    income: 90000,
  },
  {
    id: 6,
    name: "Sabbir",
    age: 40,
    skill: "AI devs",
    location: "Khulna",
    income: 100000,
  },
];
